### ISSUE TITLE
WebSQL is gone too

### ISSUE THREAD

**Issue by sylvainpolletvillard** [chrisabrams/dragon#11]
http://www.w3.org/TR/webdatabase/

WebSQL has been dropped by W3C a few years ago. IndexedDB is often used in replacement but it may be overkill for this project. Better use localStorage and Service Workers for persistant data storage.

**Comment by chrisabrams** [comment]
???? This project doesn't use WebSQL.

**Comment by sylvainpolletvillard** [comment]
It's on the README, section Mixin Ideas for Models

**Comment by chrisabrams** [comment]
Gotcha. Removed that. I have no recollection of putting that in the list, but yes, its moot now.
