### ISSUE TITLE
Integrating with diffhtml instead of virtual-dom

### ISSUE THREAD

**Issue by tbranyen** [chrisabrams/dragon#7]
I've been experimenting with a project called [diffhtml](https://github.com/tbranyen/diffhtml) that provides an interface to DOM diff and patch view changes (very much like virtual-dom). Right now it's far from being production ready, but is more feature-rich than virtual-dom and IMO a much more elegant interface. For instance, virtual-dom did not support data attributes the last time I used it (not sure if this has been fixed since), is quite large, and requires converting HTML to hyperscript in order to actually diff (I see you're using html-to-vdom in the view layer). virtual-dom also does not attempt to polyfill Custom Elements or provide a transitions API.

You can investigate the GitHub page to see more details, or check out [this demo repository](https://github.com/tbranyen/chart-component) to see some interesting usage of the transitions API and Custom Elements.

I'd love to help prototype a build that includes this, only because I find the interface is much more practical and elegant than virtual-dom's. I'm still actively working on diffhtml, so if you decide to give it a go, ping me and I'd be happy to help contribute in any way.

**Comment by chrisabrams** [comment]
I'm going to try this out. I'm not happy with how `virtual-dom` handles diffing.

**Comment by chrisabrams** [comment]
We're going with Incremental DOM, but thanks for pointing out your project! Was fun to learn.
